# Generated by Django 5.2.4 on 2025-09-03 21:48

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('student_uuid', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('surname', models.CharField(max_length=100)),
                ('first_name', models.CharField(max_length=100)),
                ('middle_name', models.CharField(blank=True, max_length=100, null=True)),
                ('email', models.EmailField(blank=True, max_length=255, null=True, unique=True)),
                ('registration_number', models.CharField(max_length=20, unique=True)),
                ('department', models.CharField(max_length=255)),
                ('program', models.CharField(max_length=255)),
                ('soma_class_code', models.CharField(blank=True, max_length=20, null=True)),
                ('academic_year_status', models.CharField(choices=[('Continuing', 'Continuing'), ('Retake', 'Retake'), ('Deferred', 'Deferred'), ('Probation', 'Probation'), ('Completed', 'Completed')], default='Continuing', max_length=20)),
                ('student_status', models.CharField(choices=[('Enrolled', 'Enrolled'), ('Withdrawn', 'Withdrawn'), ('Suspended', 'Suspended')], default='Enrolled', max_length=20)),
                ('year_of_study', models.IntegerField(blank=True, null=True)),
                ('admission_date', models.DateField(blank=True, null=True)),
                ('expected_graduation_date', models.DateField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'indexes': [models.Index(fields=['registration_number'], name='students_st_registr_23d894_idx'), models.Index(fields=['surname', 'first_name'], name='students_st_surname_f4cba6_idx')],
            },
        ),
    ]
