# Generated by Django 5.2.6 on 2025-09-12 09:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='student',
            name='admission_date',
        ),
        migrations.RemoveField(
            model_name='student',
            name='expected_graduation_date',
        ),
        migrations.RemoveField(
            model_name='student',
            name='year_of_study',
        ),
    ]
