# Generated by Django 5.2.6 on 2025-09-18 13:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0002_remove_student_admission_date_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='student',
            name='email',
        ),
        migrations.AddField(
            model_name='student',
            name='mobile_phone',
            field=models.CharField(blank=True, help_text='Your Active Mobile Phone number', max_length=15, null=True),
        ),
        migrations.AlterField(
            model_name='student',
            name='academic_year_status',
            field=models.CharField(choices=[('Continuing', 'Continuing'), ('Retake', 'Retake'), ('Deferred', 'Deferred'), ('Probation', 'Probation'), ('Completed', 'Completed')], default='Continuing', help_text='Your Status in Academic Year 2024/25', max_length=20),
        ),
        migrations.AlterField(
            model_name='student',
            name='department',
            field=models.CharField(help_text='Your Department', max_length=255),
        ),
        migrations.AlterField(
            model_name='student',
            name='first_name',
            field=models.CharField(help_text='Your First Name', max_length=100),
        ),
        migrations.AlterField(
            model_name='student',
            name='middle_name',
            field=models.CharField(blank=True, help_text='Your Middle Name', max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='student',
            name='program',
            field=models.CharField(help_text='Your Academic Program', max_length=255),
        ),
        migrations.AlterField(
            model_name='student',
            name='registration_number',
            field=models.CharField(help_text='Your Registration Number', max_length=20, unique=True),
        ),
        migrations.AlterField(
            model_name='student',
            name='soma_class_code',
            field=models.CharField(blank=True, help_text='Your SOMA Class (e.g., OD24CE, BENG24EE, ME24SE etc)', max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='student',
            name='surname',
            field=models.CharField(help_text='Your Surname', max_length=100),
        ),
        migrations.AddIndex(
            model_name='student',
            index=models.Index(fields=['mobile_phone'], name='students_st_mobile__d48b51_idx'),
        ),
        migrations.AddIndex(
            model_name='student',
            index=models.Index(fields=['department'], name='students_st_departm_c67345_idx'),
        ),
    ]
