# Generated by Django 5.2.6 on 2025-09-18 13:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0003_remove_student_email_student_mobile_phone_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='student',
            name='program',
        ),
    ]
