# Generated by Django 5.0.7 on 2025-08-25 19:19

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SecurityPersonnel',
            fields=[
                ('security_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('employee_id', models.CharField(max_length=50, unique=True)),
                ('badge_number', models.CharField(max_length=50, unique=True)),
                ('full_name', models.CharField(max_length=255)),
                ('phone_number', models.CharField(blank=True, max_length=20, null=True)),
                ('hire_date', models.DateField(blank=True, null=True)),
                ('termination_date', models.DateField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'indexes': [models.Index(fields=['employee_id'], name='idx_security_employee_id'), models.Index(fields=['badge_number'], name='idx_security_badge'), models.Index(fields=['is_active'], name='idx_security_active'), models.Index(fields=['deleted_at'], name='idx_security_deleted')],
            },
        ),
        migrations.AddConstraint(
            model_name='securitypersonnel',
            constraint=models.CheckConstraint(check=models.Q(('termination_date__isnull', True), ('hire_date__isnull', True), ('termination_date__gte', models.F('hire_date')), _connector='OR'), name='check_security_termination_after_hire'),
        ),
    ]
