# Generated by Django 5.2.4 on 2025-08-29 10:23

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adminstrator', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='PhysicalLocations',
            fields=[
                ('location_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('location_name', models.CharField(max_length=255)),
                ('location_type', models.CharField(choices=[('campus', 'Campus'), ('building', 'Building'), ('floor', 'Floor'), ('room', 'Room'), ('gate', 'Gate'), ('area', 'Area')], max_length=20)),
                ('description', models.TextField(blank=True, null=True)),
                ('is_restricted', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'indexes': [models.Index(fields=['location_name'], name='idx_physical_locations_name'), models.Index(fields=['location_type'], name='idx_physical_locations_type'), models.Index(fields=['deleted_at'], name='idx_physical_locations_deleted')],
                'constraints': [models.CheckConstraint(condition=models.Q(('location_type__in', ['campus', 'building', 'floor', 'room', 'gate', 'area'])), name='check_physical_locations_type')],
            },
        ),
        migrations.CreateModel(
            name='AccessGates',
            fields=[
                ('gate_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('gate_code', models.CharField(max_length=20, unique=True)),
                ('gate_name', models.CharField(max_length=100)),
                ('gate_type', models.CharField(choices=[('entry', 'Entry'), ('exit', 'Exit'), ('bidirectional', 'Bidirectional')], default='bidirectional', max_length=20)),
                ('hardware_id', models.CharField(max_length=100, unique=True)),
                ('ip_address', models.CharField(blank=True, max_length=45, null=True)),
                ('mac_address', models.CharField(blank=True, max_length=17, null=True)),
                ('status', models.CharField(choices=[('active', 'Active'), ('inactive', 'Inactive'), ('maintenance', 'Maintenance'), ('error', 'Error')], default='active', max_length=20)),
                ('emergency_override_enabled', models.BooleanField(default=False)),
                ('backup_power_available', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('location', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='adminstrator.physicallocations')),
            ],
            options={
                'indexes': [models.Index(fields=['gate_code'], name='idx_access_gates_code'), models.Index(fields=['location'], name='idx_access_gates_location'), models.Index(fields=['hardware_id'], name='idx_access_gates_hardware'), models.Index(fields=['status'], name='idx_access_gates_status'), models.Index(fields=['deleted_at'], name='idx_access_gates_deleted')],
                'constraints': [models.CheckConstraint(condition=models.Q(('gate_type__in', ['entry', 'exit', 'bidirectional'])), name='check_access_gates_type'), models.CheckConstraint(condition=models.Q(('status__in', ['active', 'inactive', 'maintenance', 'error'])), name='check_access_gates_status')],
            },
        ),
    ]
