# Generated by Django 5.2.6 on 2025-09-19 15:18

import django.db.models.deletion
import django.utils.timezone
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('cardmanage', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AccessLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('log_uuid', models.UUIDField(default=uuid.uuid4, editable=False, help_text='Unique identifier for the access log entry', unique=True)),
                ('rfid_number', models.CharField(db_index=True, help_text='RFID number that was scanned', max_length=50)),
                ('access_status', models.CharField(choices=[('granted', 'Access Granted'), ('denied', 'Access Denied')], help_text='Whether access was granted or denied', max_length=20)),
                ('denial_reason', models.CharField(blank=True, choices=[('invalid_rfid', 'Invalid RFID Number'), ('card_inactive', 'Card is Inactive'), ('card_expired', 'Card has Expired'), ('student_inactive', 'Student is Inactive'), ('system_error', 'System Error')], help_text='Reason for access denial (if applicable)', max_length=30, null=True)),
                ('access_location', models.CharField(blank=True, help_text='Location where access was attempted (optional)', max_length=100, null=True)),
                ('device_identifier', models.CharField(blank=True, help_text='Identifier of the device that made the request (optional)', max_length=100, null=True)),
                ('ip_address', models.GenericIPAddressField(blank=True, help_text='IP address of the requesting device', null=True)),
                ('timestamp', models.DateTimeField(db_index=True, default=django.utils.timezone.now, help_text='Timestamp when access was attempted')),
                ('response_time_ms', models.PositiveIntegerField(blank=True, help_text='Response time in milliseconds (optional)', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('card', models.ForeignKey(blank=True, help_text='Card associated with the RFID (if found)', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='access_logs', to='cardmanage.card')),
            ],
            options={
                'verbose_name': 'Access Log',
                'verbose_name_plural': 'Access Logs',
                'ordering': ['-timestamp'],
                'indexes': [models.Index(fields=['rfid_number'], name='access_acce_rfid_nu_af4522_idx'), models.Index(fields=['access_status'], name='access_acce_access__d9e796_idx'), models.Index(fields=['timestamp'], name='access_acce_timesta_c1ca79_idx'), models.Index(fields=['card'], name='access_acce_card_id_c04812_idx')],
            },
        ),
    ]
