# Generated by Django 5.2.6 on 2025-09-19 15:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('access', '0001_initial'),
        ('cardmanage', '0001_initial'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='accesslog',
            index=models.Index(fields=['rfid_number', 'timestamp'], name='access_acce_rfid_nu_2ef008_idx'),
        ),
        migrations.AddIndex(
            model_name='accesslog',
            index=models.Index(fields=['access_status', 'timestamp'], name='access_acce_access__27dce6_idx'),
        ),
    ]
