# Generated by Django 5.2.6 on 2025-10-10 13:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('access', '0001_initial'),
        ('cardmanage', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='accesslog',
            name='card',
            field=models.ForeignKey(blank=True, help_text='Card associated with the RFID (if found)', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='access_logs', to='cardmanage.card'),
        ),
        migrations.AddIndex(
            model_name='accesslog',
            index=models.Index(fields=['rfid_number'], name='access_acce_rfid_nu_af4522_idx'),
        ),
        migrations.AddIndex(
            model_name='accesslog',
            index=models.Index(fields=['access_status'], name='access_acce_access__d9e796_idx'),
        ),
        migrations.AddIndex(
            model_name='accesslog',
            index=models.Index(fields=['timestamp'], name='access_acce_timesta_c1ca79_idx'),
        ),
        migrations.AddIndex(
            model_name='accesslog',
            index=models.Index(fields=['card'], name='access_acce_card_id_c04812_idx'),
        ),
        migrations.AddIndex(
            model_name='accesslog',
            index=models.Index(fields=['rfid_number', 'timestamp'], name='access_acce_rfid_nu_2ef008_idx'),
        ),
        migrations.AddIndex(
            model_name='accesslog',
            index=models.Index(fields=['access_status', 'timestamp'], name='access_acce_access__27dce6_idx'),
        ),
    ]
