# Generated by Django 5.2.4 on 2025-08-06 10:45

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authenication', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='RegistrationOfficer',
            fields=[
                ('officer_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('username', models.CharField(max_length=50, unique=True)),
                ('full_name', models.CharField(max_length=255)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('phone_number', models.CharField(blank=True, max_length=20, null=True)),
                ('password_hash', models.CharField(max_length=255)),
                ('salt', models.CharField(blank=True, max_length=255, null=True)),
                ('password_changed_at', models.DateTimeField(auto_now_add=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'db_table': 'registration_officers',
                'indexes': [models.Index(fields=['username'], name='registratio_usernam_8168f5_idx'), models.Index(fields=['email'], name='registratio_email_199b62_idx'), models.Index(fields=['is_active'], name='registratio_is_acti_93f48d_idx'), models.Index(fields=['deleted_at'], name='registratio_deleted_023261_idx')],
            },
        ),
    ]
