# Generated by Django 5.2.4 on 2025-08-25 12:00

from django.db import migrations

def migrate_users(apps, schema_editor):
    Administrator = apps.get_model('authenication', 'Administrator')
    RegistrationOfficer = apps.get_model('authenication', 'RegistrationOfficer')
    User = apps.get_model('authenication', 'User')

    for admin in Administrator.objects.all():
        User.objects.create(
            id=admin.admin_id,
            username=admin.username,
            full_name=admin.full_name,
            email=admin.email,
            phone_number=admin.phone_number,
            password=admin.password_hash,
            user_type='administrator',
            password_changed_at=admin.password_changed_at,
            failed_login_attempts=admin.failed_login_attempts,
            account_locked=admin.account_locked,
            account_locked_until=admin.account_locked_until,
            is_active=admin.is_active,
            is_staff=True,
            created_at=admin.created_at,
            updated_at=admin.updated_at,
            deleted_at=admin.deleted_at,
            last_login=admin.last_login,
        )

    for officer in RegistrationOfficer.objects.all():
        User.objects.create(
            id=officer.officer_id,
            username=officer.username,
            full_name=officer.full_name,
            email=officer.email,
            phone_number=officer.phone_number,
            password=officer.password_hash,
            user_type='registration_officer',
            password_changed_at=officer.password_changed_at,
            is_active=officer.is_active,
            is_staff=False,
            created_at=officer.created_at,
            updated_at=officer.updated_at,
            deleted_at=officer.deleted_at,
        )

class Migration(migrations.Migration):

    dependencies = [
        ('authenication', '0003_user'),
    ]

    operations = [
        migrations.RunPython(migrate_users),
    ]