# Generated by Django 5.0.7 on 2025-08-25 13:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('authenication', '0004_migrate_users'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Administrator',
        ),
        migrations.DeleteModel(
            name='RegistrationOfficer',
        ),
    ]
