# Generated by Django 5.2.6 on 2025-10-10 09:18

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Staff',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('staff_uuid', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('surname', models.CharField(max_length=100)),
                ('first_name', models.CharField(max_length=100)),
                ('middle_name', models.CharField(blank=True, max_length=100, null=True)),
                ('mobile_phone', models.CharField(blank=True, max_length=15, null=True)),
                ('staff_number', models.CharField(max_length=20, unique=True)),
                ('department', models.CharField(max_length=255)),
                ('position', models.CharField(max_length=100)),
                ('employment_status', models.CharField(choices=[('Active', 'Active'), ('Inactive', 'Inactive'), ('Terminated', 'Terminated'), ('Retired', 'Retired'), ('On Leave', 'On Leave')], default='Active', max_length=50)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'indexes': [models.Index(fields=['staff_number'], name='staff_staff_staff_n_115003_idx'), models.Index(fields=['surname', 'first_name'], name='staff_staff_surname_3b2a7c_idx'), models.Index(fields=['mobile_phone'], name='staff_staff_mobile__51e54a_idx'), models.Index(fields=['department'], name='staff_staff_departm_eea1cc_idx')],
            },
        ),
        migrations.CreateModel(
            name='StaffPhoto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('photo', models.ImageField(blank=True, null=True, upload_to='staff_photos/')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('staff', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='photo', to='staff.staff')),
            ],
        ),
    ]
