# Generated by Django 5.2.6 on 2025-09-19 11:46

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('students', '0004_remove_student_program'),
    ]

    operations = [
        migrations.CreateModel(
            name='Card',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('card_uuid', models.UUIDField(default=uuid.uuid4, editable=False, help_text='Unique identifier for the card', unique=True)),
                ('rfid_number', models.CharField(help_text='RFID number of the physical card', max_length=50, unique=True)),
                ('is_active', models.BooleanField(default=True, help_text='Whether the card is currently active')),
                ('issued_date', models.DateTimeField(auto_now_add=True, help_text='Date when the card was issued')),
                ('expiry_date', models.DateTimeField(blank=True, help_text='Date when the card expires (optional)', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('student', models.OneToOneField(help_text='Student associated with this card', on_delete=django.db.models.deletion.CASCADE, related_name='card', to='students.student')),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['rfid_number'], name='cardmanage__rfid_nu_f33cf7_idx'), models.Index(fields=['card_uuid'], name='cardmanage__card_uu_0e5cc6_idx'), models.Index(fields=['is_active'], name='cardmanage__is_acti_049d53_idx'), models.Index(fields=['student'], name='cardmanage__student_93bafb_idx')],
            },
        ),
    ]
