# Generated by Django 5.2.6 on 2025-10-10 13:11

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('adminstrator', '0002_physicallocations_accessgates'),
        ('staff', '0001_initial'),
        ('students', '0005_studentphoto'),
    ]

    operations = [
        migrations.CreateModel(
            name='Card',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('card_uuid', models.UUIDField(default=uuid.uuid4, editable=False, help_text='Unique identifier for the card', unique=True)),
                ('rfid_number', models.CharField(db_index=True, help_text='RFID number of the physical card', max_length=50, unique=True)),
                ('card_type', models.CharField(choices=[('student', 'Student'), ('staff', 'Staff'), ('security', 'Security Personnel')], help_text='Type of card (student, staff, security)', max_length=20)),
                ('is_active', models.BooleanField(default=True, help_text='Whether the card is currently active')),
                ('issued_date', models.DateTimeField(auto_now_add=True, help_text='Date when the card was issued')),
                ('expiry_date', models.DateTimeField(blank=True, help_text='Date when the card expires (optional)', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('security_personnel', models.OneToOneField(blank=True, help_text='Security personnel associated with this card', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='card', to='adminstrator.securitypersonnel')),
                ('staff', models.OneToOneField(blank=True, help_text='Staff member associated with this card', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='card', to='staff.staff')),
                ('student', models.OneToOneField(blank=True, help_text='Student associated with this card', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='card', to='students.student')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='IDCardPrintLog',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('printed_at', models.DateTimeField(auto_now_add=True)),
                ('printed_by', models.CharField(help_text='Username of who printed the card', max_length=255)),
                ('user_type', models.CharField(help_text='User type (administrator/registration_officer)', max_length=50)),
                ('pdf_generated', models.BooleanField(default=True)),
                ('card', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='print_logs', to='cardmanage.card')),
                ('security_personnel', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='card_print_logs', to='adminstrator.securitypersonnel')),
                ('staff', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='card_print_logs', to='staff.staff')),
                ('student', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='card_print_logs', to='students.student')),
            ],
            options={
                'ordering': ['-printed_at'],
            },
        ),
        migrations.CreateModel(
            name='IDCardVerificationLog',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('verified_at', models.DateTimeField(auto_now_add=True)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('user_agent', models.TextField(blank=True, help_text='Browser/device information', null=True)),
                ('verification_source', models.CharField(default='qr_scan', help_text='How verification was initiated (qr_scan, direct_link, etc)', max_length=50)),
                ('security_personnel', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='verification_logs', to='adminstrator.securitypersonnel')),
                ('staff', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='verification_logs', to='staff.staff')),
                ('student', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='verification_logs', to='students.student')),
            ],
            options={
                'ordering': ['-verified_at'],
            },
        ),
        migrations.AddIndex(
            model_name='card',
            index=models.Index(fields=['rfid_number'], name='cardmanage__rfid_nu_f33cf7_idx'),
        ),
        migrations.AddIndex(
            model_name='card',
            index=models.Index(fields=['card_uuid'], name='cardmanage__card_uu_0e5cc6_idx'),
        ),
        migrations.AddIndex(
            model_name='card',
            index=models.Index(fields=['is_active'], name='cardmanage__is_acti_049d53_idx'),
        ),
        migrations.AddIndex(
            model_name='card',
            index=models.Index(fields=['card_type'], name='cardmanage__card_ty_a7abc6_idx'),
        ),
        migrations.AddIndex(
            model_name='card',
            index=models.Index(fields=['student'], name='cardmanage__student_93bafb_idx'),
        ),
        migrations.AddIndex(
            model_name='card',
            index=models.Index(fields=['staff'], name='cardmanage__staff_i_b5628a_idx'),
        ),
        migrations.AddIndex(
            model_name='card',
            index=models.Index(fields=['security_personnel'], name='cardmanage__securit_5e6bbc_idx'),
        ),
        migrations.AddConstraint(
            model_name='card',
            constraint=models.CheckConstraint(condition=models.Q(('card_type__in', ['student', 'staff', 'security'])), name='check_card_type_valid'),
        ),
        migrations.AddIndex(
            model_name='idcardprintlog',
            index=models.Index(fields=['card'], name='cardmanage__card_id_82be68_idx'),
        ),
        migrations.AddIndex(
            model_name='idcardprintlog',
            index=models.Index(fields=['student'], name='cardmanage__student_6e0bbf_idx'),
        ),
        migrations.AddIndex(
            model_name='idcardprintlog',
            index=models.Index(fields=['printed_at'], name='cardmanage__printed_547c9a_idx'),
        ),
        migrations.AddIndex(
            model_name='idcardverificationlog',
            index=models.Index(fields=['student'], name='cardmanage__student_47b17a_idx'),
        ),
        migrations.AddIndex(
            model_name='idcardverificationlog',
            index=models.Index(fields=['verified_at'], name='cardmanage__verifie_856914_idx'),
        ),
    ]
