# Generated by Django 5.2.6 on 2025-09-19 15:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cardmanage', '0001_initial'),
        ('students', '0004_remove_student_program'),
    ]

    operations = [
        migrations.AlterField(
            model_name='card',
            name='is_active',
            field=models.BooleanField(db_index=True, default=True, help_text='Whether the card is currently active'),
        ),
        migrations.AlterField(
            model_name='card',
            name='rfid_number',
            field=models.CharField(db_index=True, help_text='RFID number of the physical card', max_length=50, unique=True),
        ),
        migrations.AddIndex(
            model_name='card',
            index=models.Index(fields=['rfid_number', 'is_active'], name='cardmanage__rfid_nu_253eef_idx'),
        ),
    ]
