# Generated by Django 5.2.6 on 2025-10-08 11:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cardmanage', '0002_alter_card_is_active_alter_card_rfid_number_and_more'),
        ('students', '0005_studentphoto'),
    ]

    operations = [
        migrations.CreateModel(
            name='IDCardPrintLog',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('printed_at', models.DateTimeField(auto_now_add=True)),
                ('printed_by', models.CharField(help_text='Username of who printed the card', max_length=255)),
                ('user_type', models.CharField(help_text='User type (administrator/registration_officer)', max_length=50)),
                ('pdf_generated', models.BooleanField(default=True)),
            ],
            options={
                'ordering': ['-printed_at'],
            },
        ),
        migrations.CreateModel(
            name='IDCardVerificationLog',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('verified_at', models.DateTimeField(auto_now_add=True)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('user_agent', models.TextField(blank=True, help_text='Browser/device information', null=True)),
                ('verification_source', models.CharField(default='qr_scan', help_text='How verification was initiated (qr_scan, direct_link, etc)', max_length=50)),
            ],
            options={
                'ordering': ['-verified_at'],
            },
        ),
        migrations.RemoveIndex(
            model_name='card',
            name='cardmanage__rfid_nu_253eef_idx',
        ),
        migrations.AlterField(
            model_name='card',
            name='is_active',
            field=models.BooleanField(default=True, help_text='Whether the card is currently active'),
        ),
        migrations.AddField(
            model_name='idcardprintlog',
            name='card',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='print_logs', to='cardmanage.card'),
        ),
        migrations.AddField(
            model_name='idcardprintlog',
            name='student',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='card_print_logs', to='students.student'),
        ),
        migrations.AddField(
            model_name='idcardverificationlog',
            name='student',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='verification_logs', to='students.student'),
        ),
        migrations.AddIndex(
            model_name='idcardprintlog',
            index=models.Index(fields=['card'], name='cardmanage__card_id_82be68_idx'),
        ),
        migrations.AddIndex(
            model_name='idcardprintlog',
            index=models.Index(fields=['student'], name='cardmanage__student_6e0bbf_idx'),
        ),
        migrations.AddIndex(
            model_name='idcardprintlog',
            index=models.Index(fields=['printed_at'], name='cardmanage__printed_547c9a_idx'),
        ),
        migrations.AddIndex(
            model_name='idcardverificationlog',
            index=models.Index(fields=['student'], name='cardmanage__student_47b17a_idx'),
        ),
        migrations.AddIndex(
            model_name='idcardverificationlog',
            index=models.Index(fields=['verified_at'], name='cardmanage__verifie_856914_idx'),
        ),
    ]
